import { db } from './db';
import { generateId } from '../utils/id';
import { useStore } from '../store/useStore';

export async function injectDemoData() {
  const count = await db.projects.count();
  if (count > 0) return; // Only inject if DB is empty

  const projectId = generateId();

  await db.projects.add({
    id: projectId,
    name: "AI Autonomous Agent Platform",
    productDescription: "An AI-driven developer tool that executes complex system infrastructure commands autonomously.",
    validationObjective: "Determine the safest UX and architectural pattern for handling potentially destructive commands generated by the AI.",
    stage: "prototyping",
    createdAt: Date.now(),
    updatedAt: Date.now()
  });

  const segmentId = generateId();
  await db.segments.add({
    id: segmentId,
    projectId,
    name: "Senior Infrastructure Engineers",
    description: "Highly experienced SREs and Platform Engineers responsible for production environments.",
    characteristics: ["uses terraform", "manages production"],
    priority: "critical"
  });

  const h1Id = generateId();
  const h2Id = generateId();

  await db.hypotheses.bulkAdd([
    {
      id: h1Id,
      projectId,
      statement: "Users will abandon the AI if they are prompted to confirm every single read-only or low-risk command.",
      category: 'other',
      status: 'strongly-supported',
      importance: 'high',
      confidenceScore: 0,
      createdAt: Date.now()
    },
    {
      id: h2Id,
      projectId,
      statement: "Users will refuse to adopt the platform if the AI can execute destructive actions (like `rm` or `drop table`) without explicit manual approval.",
      category: 'other',
      status: 'strongly-supported',
      importance: 'critical',
      confidenceScore: 0,
      createdAt: Date.now()
    }
  ]);

  const source1Id = generateId();
  const source2Id = generateId();

  await db.sources.bulkAdd([
    {
      id: source1Id,
      projectId,
      segmentId,
      participantId: "lead_sre_01",
      type: 'interview',
      date: Date.now(),
      rawText: "If this thing deletes a production database because it hallucinated a flag, I am instantly fired. It absolutely cannot run destructive commands without me clicking a button. But if you make me confirm every `ls` or `git status`, I'm just going to uninstall it because it's too slow.",
      metadata: { title: 'User Research: Platform Security' },
      tags: ["security", "ux"]
    },
    {
      id: source2Id,
      projectId,
      segmentId,
      participantId: "beta_telemetry",
      type: 'observation',
      date: Date.now(),
      rawText: "Beta cohort A (Require all confirmations): 85% churn in first hour. Users cited 'too much friction'.\nBeta cohort B (No confirmations): 1 user triggered an accidental recursive delete. Trust metric plummeted.",
      metadata: { title: 'Beta Cohort Analysis Q3' },
      tags: ["telemetry"]
    }
  ]);

  const ev1 = generateId();
  const ev2 = generateId();

  await db.evidenceSignals.bulkAdd([
    {
      id: ev1,
      projectId,
      sourceId: source1Id,
      segmentId,
      hypothesisId: h2Id,
      relationship: 'supports',
      classification: 'objection',
      statement: "Absolute blocker on autonomous destructive commands due to job security and blast radius.",
      exactExcerpt: "It absolutely cannot run destructive commands without me clicking a button.",
      isDirect: true,
      confidence: 9,
      notes: 'Clear hard-boundary requirement.',
      createdAt: Date.now(),
      provenanceState: 'exact'
    },
    {
      id: ev2,
      projectId,
      sourceId: source2Id,
      segmentId,
      hypothesisId: h1Id,
      relationship: 'supports',
      classification: 'pain',
      statement: "High friction causes immediate churn.",
      exactExcerpt: "Beta cohort A (Require all confirmations): 85% churn in first hour.",
      isDirect: true,
      confidence: 8,
      notes: 'Quantitative evidence of friction intolerance.',
      createdAt: Date.now(),
      provenanceState: 'exact'
    }
  ]);

  const decisionId = generateId();
  await db.decisions.add({
    id: decisionId,
    projectId,
    title: "Implement Risk-Tiered Execution Architecture",
    description: "Introduce a risk-assessment middleware that intercepts AI commands. Safe commands execute autonomously; high-risk commands pause execution and require explicit user confirmation.",
    reason: "We cannot compromise on production safety, but we also cannot survive the churn caused by excessive friction. A tiered approach satisfies both constraints.",
    confidence: 'high',
    status: 'accepted',
    alternatives: "1. Fully autonomous (Rejected: Unacceptable blast radius risk).\n2. Fully manual (Rejected: 85% churn rate due to friction).\n3. Sandboxed execution only (Rejected: Doesn't solve the user's actual infrastructure problems).",
    assumptions: "1. We can accurately classify command risk programmatically.\n2. Users will tolerate pausing their workflow for genuinely dangerous commands.",
    validationMethod: "A/B test the tiered architecture against Cohort C. Measure completion rate vs. user-reported safety trust scores.",
    outcome: "Pending Cohort C results.",
    createdAt: Date.now()
  });

  await db.evidenceDecisionLinks.bulkAdd([
    { id: generateId(), projectId, evidenceId: ev1, decisionId },
    { id: generateId(), projectId, evidenceId: ev2, decisionId }
  ]);

  await db.hypothesisDecisionLinks.bulkAdd([
    { id: generateId(), projectId, hypothesisId: h1Id, decisionId },
    { id: generateId(), projectId, hypothesisId: h2Id, decisionId }
  ]);

  // Set as active project
  useStore.getState().setActiveProject(projectId);
}
