import { db } from './db';
import { generateId } from '../utils/id';
import { useStore } from '../store/useStore';
import { calculateScore } from '../services/scoring';

export async function injectDemoData() {
  const count = await db.projects.count();
  if (count > 0) return; // Only inject if DB is empty

  const projectId = generateId();

  await db.projects.add({
    id: projectId,
    name: "AI Autonomous Agent Platform",
    productDescription: "An AI-driven developer tool that executes complex system infrastructure commands autonomously.",
    validationObjective: "Determine the safest UX and architectural pattern for handling potentially destructive commands generated by the AI.",
    stage: "prototyping",
    createdAt: Date.now(),
    updatedAt: Date.now()
  });

  const segmentId = generateId();
  await db.segments.add({
    id: segmentId,
    projectId,
    name: "Senior Infrastructure Engineers",
    description: "Highly experienced SREs and Platform Engineers responsible for production environments.",
    characteristics: ["uses terraform", "manages production"],
    priority: "critical"
  });

  const h1Id = generateId();
  const h2Id = generateId();

  await db.hypotheses.bulkAdd([
    {
      id: h1Id,
      projectId,
      statement: "Users will abandon the AI if they are prompted to confirm every single read-only or low-risk command.",
      category: 'other',
      status: 'strongly-supported',
      importance: 'high',
      confidenceScore: 0,
      createdAt: Date.now()
    },
    {
      id: h2Id,
      projectId,
      statement: "Users will refuse to adopt the platform if the AI can execute destructive actions (like `rm` or `drop table`) without explicit manual approval.",
      category: 'other',
      status: 'strongly-supported',
      importance: 'critical',
      confidenceScore: 0,
      createdAt: Date.now()
    }
  ]);

  const source1Id = generateId();
  const source2Id = generateId();

  await db.sources.bulkAdd([
    {
      id: source1Id,
      projectId,
      segmentId,
      participantId: "lead_sre_01",
      type: 'interview',
      date: Date.now(),
      rawText: "If this thing deletes a production database because it hallucinated a flag, I am instantly fired. It absolutely cannot run destructive commands without me clicking a button. But if you make me confirm every `ls` or `git status`, I'm just going to uninstall it because it's too slow.",
      metadata: { title: 'User Research: Platform Security' },
      tags: ["security", "ux"]
    },
    {
      id: source2Id,
      projectId,
      segmentId,
      participantId: "beta_telemetry",
      type: 'observation',
      date: Date.now(),
      rawText: "Beta cohort A (Require all confirmations): 85% churn in first hour. Users cited 'too much friction'.\nBeta cohort B (No confirmations): 1 user triggered an accidental recursive delete. Trust metric plummeted.",
      metadata: { title: 'Beta Cohort Analysis Q3' },
      tags: ["telemetry"]
    }
  ]);

  const ev1 = generateId();
  const ev2 = generateId();

  await db.evidenceSignals.bulkAdd([
    {
      id: ev1,
      projectId,
      sourceId: source1Id,
      segmentId,
      hypothesisId: h2Id,
      relationship: 'supports',
      classification: 'objection',
      statement: "Absolute blocker on autonomous destructive commands due to job security and blast radius.",
      exactExcerpt: "It absolutely cannot run destructive commands without me clicking a button.",
      isDirect: true,
      confidence: 9,
      notes: 'Clear hard-boundary requirement.',
      createdAt: Date.now(),
      provenanceState: 'exact'
    },
    {
      id: ev2,
      projectId,
      sourceId: source2Id,
      segmentId,
      hypothesisId: h1Id,
      relationship: 'supports',
      classification: 'pain',
      statement: "High friction causes immediate churn.",
      exactExcerpt: "Beta cohort A (Require all confirmations): 85% churn in first hour.",
      isDirect: true,
      confidence: 8,
      notes: 'Quantitative evidence of friction intolerance.',
      createdAt: Date.now(),
      provenanceState: 'exact'
    }
  ]);

  const decisionId = generateId();
  await db.decisions.add({
    id: decisionId,
    projectId,
    title: "Implement Risk-Tiered Execution Architecture",
    description: "Introduce a risk-assessment middleware that intercepts AI commands. Safe commands execute autonomously; high-risk commands pause execution and require explicit user confirmation.",
    reason: "We cannot compromise on production safety, but we also cannot survive the churn caused by excessive friction. A tiered approach satisfies both constraints.",
    confidence: 'high',
    status: 'accepted',
    alternatives: "1. Fully autonomous (Rejected: Unacceptable blast radius risk).\n2. Fully manual (Rejected: 85% churn rate due to friction).\n3. Sandboxed execution only (Rejected: Doesn't solve the user's actual infrastructure problems).",
    assumptions: "1. We can accurately classify command risk programmatically.\n2. Users will tolerate pausing their workflow for genuinely dangerous commands.",
    validationMethod: "A/B test the tiered architecture against Cohort C. Measure completion rate vs. user-reported safety trust scores.",
    outcome: "Pending Cohort C results.",
    createdAt: Date.now()
  });

  await db.evidenceDecisionLinks.bulkAdd([
    { id: generateId(), projectId, evidenceId: ev1, decisionId },
    { id: generateId(), projectId, evidenceId: ev2, decisionId }
  ]);

  await db.hypothesisDecisionLinks.bulkAdd([
    { id: generateId(), projectId, hypothesisId: h1Id, decisionId },
    { id: generateId(), projectId, hypothesisId: h2Id, decisionId }
  ]);

  // A second, deliberately mixed project keeps the guided demo from implying
  // that Validation Ledger only accumulates positive evidence.
  const mixedProjectId = generateId();
  const mixedSegmentId = generateId();
  const mixedHypothesisId = generateId();
  const mixedSourceIds = [generateId(), generateId(), generateId()];
  const mixedEvidenceIds = [generateId(), generateId(), generateId()];

  await db.projects.add({
    id: mixedProjectId,
    name: 'Evidence Review Workspace',
    productDescription: 'A fictional workspace for teams that review operational evidence before adopting a new workflow.',
    validationObjective: 'Determine whether a review workspace earns enough value to justify a recurring team purchase.',
    stage: 'discovery',
    createdAt: Date.now(),
    updatedAt: Date.now()
  });

  await db.segments.add({
    id: mixedSegmentId,
    projectId: mixedProjectId,
    name: 'Operations Leads',
    description: 'Fictional operations leaders responsible for repeatable review processes.',
    characteristics: ['owns review workflows', 'tracks operational risk'],
    priority: 'high'
  });

  await db.hypotheses.add({
    id: mixedHypothesisId,
    projectId: mixedProjectId,
    statement: 'Operations leads will pay for a review workspace that reduces evidence-chasing without hiding contradictory signals.',
    category: 'value proposition',
    status: 'mixed',
    importance: 'high',
    confidenceScore: 0,
    createdAt: Date.now()
  });

  const mixedSourceTexts = [
    'Pilot lead: We would pay for this if every decision links back to the source passage and the review queue stays current.',
    'Pilot observer: The team cut weekly evidence-chasing from three hours to one hour during the fictional trial.',
    'Pilot skeptic: We already keep this in a shared document, and another workspace would add maintenance work without enough return.'
  ];
  await db.sources.bulkAdd([
    {
      id: mixedSourceIds[0],
      projectId: mixedProjectId,
      segmentId: mixedSegmentId,
      participantId: 'fictional-ops-lead-a',
      type: 'interview',
      date: Date.now(),
      rawText: mixedSourceTexts[0],
      metadata: { title: 'Synthetic purchase conversation' },
      tags: ['pricing', 'traceability']
    },
    {
      id: mixedSourceIds[1],
      projectId: mixedProjectId,
      segmentId: mixedSegmentId,
      participantId: 'fictional-ops-lead-b',
      type: 'observation',
      date: Date.now(),
      rawText: mixedSourceTexts[1],
      metadata: { title: 'Synthetic workflow observation' },
      tags: ['behavior', 'workflow']
    },
    {
      id: mixedSourceIds[2],
      projectId: mixedProjectId,
      segmentId: mixedSegmentId,
      participantId: 'fictional-ops-lead-c',
      type: 'interview',
      date: Date.now(),
      rawText: mixedSourceTexts[2],
      metadata: { title: 'Synthetic contradictory interview' },
      tags: ['counterevidence', 'adoption']
    }
  ]);

  await db.evidenceSignals.bulkAdd([
    {
      id: mixedEvidenceIds[0],
      projectId: mixedProjectId,
      sourceId: mixedSourceIds[0],
      segmentId: mixedSegmentId,
      hypothesisId: mixedHypothesisId,
      relationship: 'supports',
      classification: 'willingness_to_pay',
      statement: 'A fictional buyer states a conditional willingness to pay for traceable decisions.',
      exactExcerpt: 'We would pay for this if every decision links back to the source passage and the review queue stays current.',
      isDirect: true,
      confidence: 8,
      notes: 'Synthetic behavioral signal; the condition remains an adoption risk.',
      createdAt: Date.now(),
      provenanceState: 'exact'
    },
    {
      id: mixedEvidenceIds[1],
      projectId: mixedProjectId,
      sourceId: mixedSourceIds[1],
      segmentId: mixedSegmentId,
      hypothesisId: mixedHypothesisId,
      relationship: 'supports',
      classification: 'positive_reaction',
      statement: 'A fictional observation records a measurable reduction in evidence-chasing time.',
      exactExcerpt: 'The team cut weekly evidence-chasing from three hours to one hour during the fictional trial.',
      isDirect: true,
      confidence: 7,
      notes: 'Synthetic observed behavior, not a claim about real users.',
      createdAt: Date.now(),
      provenanceState: 'exact'
    },
    {
      id: mixedEvidenceIds[2],
      projectId: mixedProjectId,
      sourceId: mixedSourceIds[2],
      segmentId: mixedSegmentId,
      hypothesisId: mixedHypothesisId,
      relationship: 'contradicts',
      classification: 'objection',
      statement: 'A fictional skeptic sees the workflow as duplicative maintenance work.',
      exactExcerpt: 'We already keep this in a shared document, and another workspace would add maintenance work without enough return.',
      isDirect: true,
      confidence: 8,
      notes: 'Material contradiction retained alongside the positive signals.',
      createdAt: Date.now(),
      provenanceState: 'exact'
    }
  ]);

  const mixedEvidence = await db.evidenceSignals.where('hypothesisId').equals(mixedHypothesisId).toArray();
  const mixedAnalysis = calculateScore(mixedEvidence);
  await db.hypotheses.update(mixedHypothesisId, {
    status: mixedAnalysis.status,
    confidenceScore: mixedAnalysis.score,
    lastReviewed: Date.now()
  });

  const mixedDecisionId = generateId();
  await db.decisions.add({
    id: mixedDecisionId,
    projectId: mixedProjectId,
    title: 'Run a bounded workflow evaluation before recurring purchase',
    description: 'Do not adopt the review workspace on synthetic evidence alone; run a bounded evaluation that tests traceability value against maintenance cost.',
    reason: 'The synthetic evidence is mixed: two signals support traceability value while one material objection says the workflow duplicates a shared document.',
    confidence: 'low',
    status: 'proposed',
    alternatives: 'Adopt immediately; stop pursuing the workspace as a standalone product.',
    assumptions: 'A concrete workflow evaluation can distinguish traceability value from added maintenance work.',
    validationMethod: 'Ask a qualified practitioner for a recent example, incumbent workflow, repeat-use trigger, and strongest reason not to use the product.',
    outcome: 'Pending external evaluation; synthetic demo only.',
    createdAt: Date.now()
  });

  await db.evidenceDecisionLinks.bulkAdd(
    mixedEvidenceIds.map((evidenceId) => ({ id: generateId(), projectId: mixedProjectId, evidenceId, decisionId: mixedDecisionId }))
  );
  await db.hypothesisDecisionLinks.add({
    id: generateId(),
    projectId: mixedProjectId,
    hypothesisId: mixedHypothesisId,
    decisionId: mixedDecisionId
  });

  // Set as active project
  useStore.getState().setActiveProject(projectId);
}

